# Generated by Django 2.1.7 on 2019-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major_category',
            field=models.CharField(choices=[('D1', '哲学'), ('D2', '经济学'), ('D3', '法学'), ('D4', '教育学'), ('D5', '文学'), ('D6', '历史学'), ('D7', '理学'), ('D8', '工学'), ('D9', '农学'), ('D10', '医学'), ('D11', '军事学'), ('D12', '管理学'), ('D13', '艺术学')], default='D1', help_text='专业大类', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_birth_day',
            field=models.CharField(default='201909', help_text='出生日期', max_length=64, null=True),
        ),
    ]
