# Generated by Django 2.1.7 on 2019-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tut_name',
            field=models.CharField(default=2, help_text='导师名称', max_length=64),
            preserve_default=False,
        ),
    ]
