# Generated by Django 2.1.7 on 2019-04-04 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20190405_0011'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['stu_number'], 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AddField(
            model_name='student',
            name='academy',
            field=models.OneToOneField(help_text='所属学院', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.Academy'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_candidate_number',
            field=models.CharField(help_text='考生号', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_card_type',
            field=models.CharField(default='身份证', help_text='身份证件类型', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_cultivating_mode',
            field=models.CharField(choices=[('C1', '专业学位')], default='C1', help_text='培养方式', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_enrollment_category',
            field=models.CharField(choices=[('E1', '定向'), ('E2', '非定向')], default='E1', help_text='录取类别', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_entrance_time',
            field=models.CharField(default='2019-09', help_text='入学时间', max_length=32),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_grade',
            field=models.CharField(default='1', help_text='年级', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_graduation_time',
            field=models.CharField(default='2021-07', help_text='毕业日期', max_length=32),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_is_achives',
            field=models.BooleanField(default=False, help_text='档案是否转到学校'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_is_regular_income',
            field=models.BooleanField(default=False, help_text='是否有固定收入'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_is_tuition_fees',
            field=models.BooleanField(default=False, help_text='是否欠缴学费'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_is_village',
            field=models.BooleanField(default=False, help_text='是否农村学生'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_learn_status',
            field=models.CharField(choices=[('D1', '博士'), ('D2', '硕士'), ('D3', '本科')], default='D2', help_text='学习阶段', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_learn_type',
            field=models.CharField(choices=[('S1', '全日制'), ('S2', '非全日制')], default='S1', help_text='学习形式', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_nation',
            field=models.CharField(default='汉', help_text='民族', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_nationality',
            field=models.CharField(default='中国', help_text='国籍', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_special_program',
            field=models.CharField(choices=[('S1', '无'), ('S2', '少数民族高层次骨干计划'), ('S3', '强军计划'), ('S4', '对口支援西部地区高校定向培养计划'), ('S5', '援藏计划'), ('S6', '农村学校教育硕士师资培养计划'), ('S7', '高校辅导员攻读思想政治教育专业硕士学位计划'), ('S8', '高校思想政治理论课教师攻读博士学位计划'), ('S9', '其他')], default='S1', help_text='专项计划', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_system',
            field=models.IntegerField(default=3, help_text='学制'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_type',
            field=models.CharField(choices=[('S1', '硕士'), ('S2', '博士'), ('S3', '本硕连读'), ('S4', '硕博连读'), ('S5', '直博')], default='S1', help_text='学生类型', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_cardID',
            field=models.CharField(default='', help_text='身份证号', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_gender',
            field=models.CharField(choices=[('G1', '男'), ('G2', '女')], help_text='性别', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_number',
            field=models.IntegerField(default='001', help_text='学号', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_political',
            field=models.CharField(choices=[('P1', '党员'), ('P2', '团员'), ('P3', '群众'), ('P4', '民主党派')], help_text='政治面貌', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_source',
            field=models.CharField(help_text='生源地', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_status',
            field=models.CharField(choices=[('S1', '在校'), ('S2', '离校'), ('S3', '留校')], default='S1', help_text='在学状态', max_length=64),
        ),
    ]
