# Generated by Django 2.1.7 on 2019-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_cardID',
            field=models.CharField(default='12345', help_text='身份证号', max_length=128, null=True, unique=True),
        ),
    ]
