# Generated by Django 2.1.7 on 2019-04-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='adjust',
            new_name='stu_is_adjust',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='exemption',
            new_name='stu_is_exemption',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='volunteer',
            new_name='stu_is_volunteer',
        ),
    ]
