# Generated by Django 2.1.7 on 2019-04-30 07:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='唯一标识ID', primary_key=True, serialize=False, unique=True)),
                ('the_title', models.CharField(help_text='课题名称', max_length=128)),
                ('the_start_time', models.DateField(help_text='开题时间')),
                ('the_mid_score', models.CharField(help_text='中期考核结果', max_length=64)),
                ('the_start_result', models.BooleanField(default=True, help_text='开题结果')),
                ('the_check_result', models.FloatField(default=0.15, help_text='查重结果')),
                ('the_blind_score1', models.CharField(help_text='盲审结果1', max_length=64)),
                ('the_blind_score2', models.CharField(help_text='盲审结果2', max_length=64)),
                ('the_exam_count', models.IntegerField(default=0, help_text='论文查重次数')),
                ('the_final_score', models.CharField(help_text='答辩成绩', max_length=64)),
                ('the_is_superb', models.BooleanField(default=False, help_text='是否优秀论文')),
                ('the_is_delay', models.BooleanField(default=False, help_text='是否延期')),
                ('the_delay_reason', models.TextField(help_text='延期原因', null=True)),
                ('student', models.OneToOneField(help_text='论文作者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis', to='users.Student')),
            ],
            options={
                'verbose_name': '论文',
                'verbose_name_plural': '论文',
            },
        ),
    ]
