# Generated by Django 2.1.7 on 2019-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='the_check_score',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='the_start_score',
        ),
        migrations.AddField(
            model_name='thesis',
            name='the_check_result',
            field=models.FloatField(default=0.15, help_text='查重结果'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='the_delay_reason',
            field=models.TextField(help_text='延期原因', null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='the_exam_count',
            field=models.IntegerField(default=0, help_text='论文查重次数'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='the_is_delay',
            field=models.BooleanField(default=False, help_text='是否延期'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='the_start_result',
            field=models.BooleanField(default=True, help_text='开题结果'),
        ),
    ]
