# Generated by Django 2.1.7 on 2019-04-13 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='唯一标识ID', primary_key=True, serialize=False, unique=True)),
                ('aca_avatar', models.CharField(help_text='学院图标', max_length=128, null=True)),
                ('aca_nickname', models.CharField(help_text='学院简称', max_length=128, null=True)),
                ('aca_cname', models.CharField(help_text='学院名称(中)', max_length=128, null=True)),
                ('aca_ename', models.CharField(help_text='学院名称(英)', max_length=128, null=True)),
                ('aca_code', models.IntegerField(help_text='学院代码', null=True)),
                ('aca_phone', models.CharField(help_text='学院电话', max_length=128, null=True)),
                ('aca_fax', models.CharField(help_text='学院传真', max_length=128, null=True)),
                ('aca_href', models.URLField(help_text='学院网址', max_length=256, null=True)),
                ('aca_brief', models.TextField(help_text='学院简介')),
                ('aca_user', models.ForeignKey(help_text='学院负责人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aca_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='唯一标识ID', primary_key=True, serialize=False, unique=True)),
                ('maj_name', models.CharField(help_text='学科名称', max_length=128, null=True)),
                ('maj_code', models.IntegerField(help_text='学科编号', null=True)),
                ('maj_type', models.CharField(choices=[('C1', '专业硕士学位'), ('C2', '学科硕士学位')], help_text='学科类型', max_length=128)),
                ('maj_first', models.BooleanField(help_text='是否一级学科')),
                ('maj_second', models.BooleanField(help_text='是否二级学科')),
                ('maj_first_uuid', models.UUIDField(help_text='所属一级学科', null=True)),
                ('maj_setup_time', models.DateField(help_text='获批时间')),
                ('maj_degree', models.CharField(choices=[('D1', '哲学'), ('D2', '经济学'), ('D3', '法学'), ('D4', '教育学'), ('D5', '文学'), ('D6', '历史学'), ('D7', '理学'), ('D8', '工学'), ('D9', '农学'), ('D10', '医学'), ('D11', '军事学'), ('D12', '管理学'), ('D13', '艺术学')], help_text='学位类型', max_length=128)),
            ],
            options={
                'verbose_name': '学科专业',
                'verbose_name_plural': '学科专业',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='唯一标识ID', primary_key=True, serialize=False, unique=True)),
                ('res_name', models.CharField(help_text='研究方向', max_length=128, null=True)),
            ],
            options={
                'verbose_name': '研究方向',
                'verbose_name_plural': '研究方向',
            },
        ),
        migrations.AddField(
            model_name='major',
            name='research',
            field=models.ManyToManyField(help_text='科研方向', related_name='research', to='academy.Research'),
        ),
        migrations.AddField(
            model_name='academy',
            name='majors',
            field=models.ManyToManyField(related_name='majors', to='academy.Major'),
        ),
    ]
