# Generated by Django 2.1.7 on 2019-05-02 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('学院管理', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MidtermExams',
        ),
        migrations.DeleteModel(
            name='OpeningReport',
        ),
        migrations.DeleteModel(
            name='PaperQuality',
        ),
        migrations.AlterModelOptions(
            name='reformresults',
            options={'default_permissions': (), 'permissions': [('can_insert_reformResult', '新增教改统计'), ('can_delete_reformResult', '删除教改统计'), ('can_update_reformResult', '修改教改统计'), ('can_search_reformResult', '查询教改统计')], 'verbose_name': '教育改革成果统计', 'verbose_name_plural': '教育改革成果统计'},
        ),
        migrations.RemoveField(
            model_name='reformresults',
            name='id',
        ),
        migrations.AddField(
            model_name='reformresults',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='唯一标识ID', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reformresults',
            name='academy',
            field=models.ForeignKey(help_text='学院名称', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rr_academy', to='学院管理.Academy'),
        ),
        migrations.AlterField(
            model_name='reformresults',
            name='time',
            field=models.DateField(default='2019', help_text='年份'),
        ),
        migrations.AlterModelTable(
            name='reformresults',
            table='reformResult',
        ),
    ]
