# Generated by Django 2.1.7 on 2019-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='aca_avatar',
            field=models.CharField(help_text='学院图标', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='academy',
            name='aca_user',
            field=models.CharField(help_text='学院负责人', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='maj_first_uuid',
            field=models.UUIDField(help_text='所属一级学科', null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='research',
            field=models.ManyToManyField(help_text='科研方向', related_name='research', to='academy.Research'),
        ),
    ]
