# Generated by Django 2.1.7 on 2019-04-08 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20190408_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='aca_user',
            field=models.ForeignKey(help_text='学院负责人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aca_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
