# Generated by Django 2.1.7 on 2019-04-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20190405_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='major',
            field=models.ManyToManyField(related_name='majors', to='academy.Major'),
        ),
    ]
