# Generated by Django 2.1.7 on 2019-04-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20190405_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academy',
            old_name='major',
            new_name='majors',
        ),
    ]
