# Generated by Django 2.1.7 on 2019-05-09 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('学院管理', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='唯一标识ID')),
                ('edu_begin_time', models.DateField(verbose_name='开始时间')),
                ('edu_finish_time', models.DateField(verbose_name='结束时间')),
                ('edu_school_name', models.CharField(max_length=128, null=True, verbose_name='学校名称')),
                ('edu_study_major', models.CharField(max_length=128, null=True, verbose_name='专业方向')),
                ('edu_study_field', models.CharField(max_length=128, null=True, verbose_name='研究领域')),
            ],
            options={
                'verbose_name': '学习经历',
                'verbose_name_plural': '学习经历',
                'db_table': 'education',
                'permissions': [('can_insert_education', '新增学习经历'), ('can_delete_education', '删除学习经历'), ('can_update_education', '修改学习经历'), ('can_search_education', '查询学习经历')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MidCheckReport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='唯一标识ID')),
                ('time', models.DateField(default='2019', verbose_name='年份')),
                ('schedule_count', models.IntegerField(default=0, verbose_name='按期考核人数')),
                ('pass_count', models.IntegerField(default=0, verbose_name='延期考核人数')),
                ('pass_proportion', models.IntegerField(default=0, verbose_name='延期考核比例')),
                ('delay_count', models.IntegerField(default=0, verbose_name='延期考核人数')),
                ('delay_proportion', models.IntegerField(default=0, verbose_name='延期考核比例')),
                ('track_count', models.IntegerField(default=0, verbose_name='被跟踪人数')),
                ('track_proportion', models.IntegerField(default=0, verbose_name='被跟踪比例')),
                ('fail_count', models.IntegerField(default=0, verbose_name='不合格人数')),
                ('fail_proportion', models.IntegerField(default=0, verbose_name='不合格比例')),
            ],
            options={
                'verbose_name': '中期考核统计',
                'verbose_name_plural': '中期考核统计',
                'db_table': 'mid_check_report',
                'permissions': [('can_insert_mid_check_report', '新增中期考核统计'), ('can_delete_mid_check_report', '删除中期考核统计'), ('can_update_mid_check_report', '修改中期考核统计'), ('can_search_mid_check_report', '查询中期考核统计')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='唯一标识ID')),
                ('stu_name', models.CharField(max_length=64, null=True, verbose_name='学生名称')),
                ('stu_number', models.IntegerField(default='20190101', null=True, unique=True, verbose_name='学号')),
                ('stu_avatar', models.ImageField(default='default.png', null=True, upload_to='students', verbose_name='学生照片')),
                ('stu_gender', models.CharField(choices=[('G1', '男'), ('G2', '女')], max_length=64, null=True, verbose_name='性别')),
                ('stu_telephone', models.IntegerField(null=True, verbose_name='电话号码')),
                ('stu_card_type', models.CharField(default='身份证', max_length=128, null=True, verbose_name='身份证件类型')),
                ('stu_cardID', models.CharField(default='', max_length=128, null=True, unique=True, verbose_name='身份证号')),
                ('stu_candidate_number', models.CharField(max_length=128, null=True, verbose_name='考生号')),
                ('stu_birth_day', models.DateField(default='201909', max_length=64, null=True, verbose_name='出生日期')),
                ('stu_nation', models.CharField(default='汉', max_length=64, null=True, verbose_name='民族')),
                ('stu_source', models.CharField(max_length=128, null=True, verbose_name='生源地')),
                ('stu_is_village', models.BooleanField(null=True, verbose_name='是否农村学生')),
                ('stu_political', models.CharField(choices=[('P1', '党员'), ('P2', '团员'), ('P3', '群众'), ('P4', '民主党派')], max_length=64, null=True, verbose_name='政治面貌')),
                ('stu_type', models.CharField(choices=[('S1', '硕士'), ('S2', '博士'), ('S3', '本硕连读'), ('S4', '硕博连读'), ('S5', '直博')], default='S1', max_length=128, null=True, verbose_name='学生类型')),
                ('stu_learn_type', models.CharField(choices=[('S1', '全日制'), ('S2', '非全日制')], default='S1', max_length=64, null=True, verbose_name='学习形式')),
                ('stu_learn_status', models.CharField(choices=[('D1', '博士'), ('D2', '硕士'), ('D3', '本科')], default='D2', max_length=64, null=True, verbose_name='学习阶段')),
                ('stu_grade', models.CharField(default='1', max_length=64, null=True, verbose_name='年级')),
                ('stu_system', models.IntegerField(default=3, null=True, verbose_name='学制')),
                ('stu_entrance_time', models.DateField(default='2019-09', max_length=32, null=True, verbose_name='入学日期')),
                ('stu_graduation_time', models.DateField(default='2021-07', max_length=32, null=True, verbose_name='毕业日期')),
                ('stu_cultivating_mode', models.CharField(choices=[('C1', '专硕'), ('C2', '学硕')], default='C1', max_length=128, null=True, verbose_name='培养方式')),
                ('stu_enrollment_category', models.CharField(choices=[('E1', '定向'), ('E2', '非定向')], default='E1', max_length=64, null=True, verbose_name='录取类别')),
                ('stu_nationality', models.CharField(default='中国', max_length=128, null=True, verbose_name='国籍')),
                ('stu_special_program', models.CharField(choices=[('S1', '无'), ('S2', '少数民族高层次骨干计划'), ('S3', '强军计划'), ('S4', '对口支援西部地区高校定向培养计划'), ('S5', '援藏计划'), ('S6', '农村学校教育硕士师资培养计划'), ('S7', '高校辅导员攻读思想政治教育专业硕士学位计划'), ('S8', '高校思想政治理论课教师攻读博士学位计划'), ('S9', '其他')], default='S1', max_length=128, null=True, verbose_name='专项计划')),
                ('stu_is_regular_income', models.BooleanField(default=False, verbose_name='是否有固定收入')),
                ('stu_is_tuition_fees', models.BooleanField(default=False, verbose_name='是否欠缴学费')),
                ('stu_is_archives', models.BooleanField(default=False, verbose_name='档案是否转到学校')),
                ('stu_is_exemption', models.BooleanField(default=False, verbose_name='是否推免生')),
                ('stu_is_adjust', models.BooleanField(default=False, verbose_name='是否调剂')),
                ('stu_is_volunteer', models.BooleanField(default=True, verbose_name='是否第一志愿')),
                ('stu_is_superb', models.BooleanField(default=False, verbose_name='是否优秀毕业生')),
                ('stu_is_delay', models.BooleanField(default=True, verbose_name='是否延期（中期考核）')),
                ('stu_delay_reason', models.CharField(max_length=255, null=True, verbose_name='中期考核延期原因')),
                ('stu_mid_check', models.CharField(choices=[('S1', '合格'), ('S2', '跟踪'), ('S3', '不合格')], max_length=64, null=True, verbose_name='中期考核结果')),
                ('stu_status', models.CharField(choices=[('S1', '在校'), ('S2', '离校'), ('S3', '留校')], default='S1', max_length=64, null=True, verbose_name='在学状态')),
                ('stu_gain_diploma', models.BooleanField(default=False, null=True, verbose_name='学位证')),
                ('stu_gain_cert', models.BooleanField(default=False, null=True, verbose_name='毕业证')),
                ('stu_academy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stu_academy', to='学院管理.Academy', verbose_name='所属学院')),
                ('stu_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stu_class', to='学院管理.Class', verbose_name='所属班级')),
                ('stu_major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stu_major', to='学院管理.Major', verbose_name='所属专业')),
                ('stu_research', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stu_research', to='学院管理.Research', verbose_name='科研方向')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
                'ordering': ['stu_number'],
                'permissions': [('can_insert_student', '新增学生'), ('can_delete_student', '删除学生'), ('can_update_student', '修改学生'), ('can_search_student', '查询学生')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='唯一标识ID')),
                ('tut_name', models.CharField(max_length=64, null=True, verbose_name='导师名称')),
                ('tut_avatar', models.ImageField(default='default.png', null=True, upload_to='teachers', verbose_name='教师图片')),
                ('tut_birth_day', models.DateField(max_length=128, null=True, verbose_name='出生日期')),
                ('tut_entry_day', models.DateField(max_length=128, null=True, verbose_name='入职日期')),
                ('tut_telephone', models.IntegerField(null=True, verbose_name='电话号码')),
                ('tut_number', models.IntegerField(null=True, unique=True, verbose_name='导师工号')),
                ('tut_cardID', models.CharField(max_length=128, null=True, unique=True, verbose_name='身份证号')),
                ('tut_gender', models.CharField(choices=[('G1', '男'), ('G2', '女')], max_length=64, verbose_name='性别')),
                ('tut_title', models.CharField(choices=[('T1', '讲师'), ('T2', '副教授'), ('T3', '教授'), ('T4', '副研究员'), ('T5', '研究员'), ('T6', '助教')], max_length=64, verbose_name='职称')),
                ('tut_political', models.CharField(choices=[('P1', '党员'), ('P2', '团员'), ('P3', '群众'), ('P4', '民主党派')], max_length=64, verbose_name='政治面貌')),
                ('tut_degree', models.CharField(choices=[('D1', '博士'), ('D2', '硕士'), ('D3', '本科')], max_length=64, verbose_name='学位')),
                ('academy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academy', to='学院管理.Academy', verbose_name='所属学院')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='用户管理.Education', verbose_name='学历')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '导师',
                'verbose_name_plural': '导师',
                'db_table': 'teacher',
                'ordering': ['tut_number'],
                'permissions': [('can_insert_tutor', '新增导师'), ('can_delete_tutor', '删除导师'), ('can_update_tutor', '修改导师'), ('can_search_tutor', '查询导师')],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='stu_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stu_tutor', to='用户管理.Tutor', verbose_name='指导老师'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
